# ============================
# Configuración general
# ============================

ARCH        ?= x86                        # o riscv
BUILD_DIR   = build/$(ARCH)
DEF_INCS     = -Ipublic -Istd

KERNEL_DISK_PATH=.kernel_disk/disk.txt

NCPU ?= 1
CPU_STACK_PAGES = 32
CPU_TRAP_STACK_PAGES = 32

# ----------------------------
# Compiladores por arquitectura
# ----------------------------
# -no-reboot -no-shutdown

ifeq ($(ARCH),x86)
	CC      = gcc
	AS      = nasm
	CFLAGS  = $(DEF_INCS) -Imeta/gen -Iarch/x86 -Iarch/x86/drivers -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector \
	           -nostartfiles -nodefaultlibs -Wall -Wextra -c -g -DIS_X86 -march=i386 -mtune=i386\
			   -DNCPU=$(NCPU)
	#CFLAGS  = $(DEF_INCS) -Imeta/gen -Iarch/x86 -Iarch/x86/drivers -m32 -nostdlib -nostdinc -fno-stack-protector \
	#           -nostartfiles -nodefaultlibs -Wall -Wextra -c -g -DIS_X86 -march=i386 -mtune=i386 -ffreestanding

	ASFLAGS = -f elf
	LDFLAGS = -T arch/x86/drivers/linker/link.ld -melf_i386
	QEMU    = qemu-system-i386 -cdrom os.iso  -m 64 -no-reboot -no-shutdown -nographic -serial mon:stdio \
								-drive file=$(KERNEL_DISK_PATH),index=1,media=disk,format=raw
else ifeq ($(ARCH),riscv)
	CC      = clang

	## Notice we also add meta/gen as include folder ! to inclider meta/apps_info.h ! with the define of the struct and apps indexs
	CFLAGS  = $(DEF_INCS) -Imeta/gen -Iarch/riscV -std=c11 -O2 -g3 -Wall -Wextra --target=riscv32-unknown-elf \
                   -fno-stack-protector -ffreestanding -nostdlib -DIS_RISC -fno-pic -fno-pie -mcmodel=medany\
				   -DNCPU=$(NCPU) \
				   -DCPU_STACK_PAGES=$(CPU_STACK_PAGES) \
				   -DCPU_TRAP_STACK_PAGES=$(CPU_TRAP_STACK_PAGES) \
	
	# If riscv then add -DIS_RISC that deifines the constant IS_RISC for conditional compiling
	
	LDFLAGS = -T arch/riscV/linker/link.ld \
          -Wl,--defsym=NCPU=$(NCPU) \
          -Wl,--defsym=CPU_STACK_PAGES=$(CPU_STACK_PAGES) \
          -Wl,--defsym=CPU_TRAP_STACK_PAGES=$(CPU_TRAP_STACK_PAGES)

	QEMU    = qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot -kernel $(BUILD_DIR)/kernel.elf \
								-smp $(NCPU) -drive id=drive0,file=$(KERNEL_DISK_PATH),format=raw,if=none \
							    -device virtio-blk-device,drive=drive0,bus=virtio-mmio-bus.0	
endif

# ============================
# Directorios fuente
# ============================


### Notice we add the meta/gen folder to look and add sources for .c with metadata previously generated by user folder makefile
ifeq ($(ARCH),x86)
	SRC_DIRS = arch/x86 arch/x86/drivers/io arch/x86/drivers/loader kernel std meta/gen arch/x86/drivers test test/test_x86
else ifeq ($(ARCH),riscv)
	SRC_DIRS = arch/riscV/drivers arch/riscV kernel std meta/gen test test/test_riscv
endif

# Buscar fuentes (.c y .s)
C_SOURCES := $(foreach dir,$(SRC_DIRS),$(wildcard $(dir)/*.c))
S_SOURCES := $(foreach dir,$(SRC_DIRS),$(wildcard $(dir)/*.s))
SOURCES   := $(C_SOURCES) $(S_SOURCES)

# Generar objetos bajo build/<arch>/... (replica la estructura original)
OBJECTS := $(patsubst %,$(BUILD_DIR)/%,$(SOURCES))
OBJECTS := $(OBJECTS:.c=.o)
OBJECTS := $(OBJECTS:.s=.o)

#Empty
USER_APPS_OBJECTS :=
USER_BUILD_FOLDER := user/build
USER_APPS_OBJECTS := $(wildcard $(USER_BUILD_FOLDER)/**/*.o)

# ifeq ($(ARCH),riscv)
# endif

# ============================
# Reglas principales
# ============================

.PHONY: all run clean os.iso

all: $(BUILD_DIR)/kernel.elf
ifeq ($(ARCH),x86)
all: os.iso
endif

# Crear carpetas necesarias (con subdirectorios)
$(BUILD_DIR):
	mkdir -p $(sort $(dir $(OBJECTS)))

# Link final
$(BUILD_DIR)/kernel.elf: $(OBJECTS)
ifeq ($(ARCH),x86)
	$(info Linking with user apps: $(USER_APPS_OBJECTS))
	ld $(LDFLAGS) $(OBJECTS) $(USER_APPS_OBJECTS) -o $@
else ifeq ($(ARCH),riscv)
	$(info Linking with user apps: $(USER_APPS_OBJECTS))
	$(CC) $(CFLAGS) $(OBJECTS) $(USER_APPS_OBJECTS) -Wl,$(LDFLAGS) -o $@
endif

# ============================
# Compilación genérica
# ============================

$(BUILD_DIR)/%.o: %.c
	mkdir -p $(dir $@)
	echo "Compilando C: $< -> $@"
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.s
	mkdir -p $(dir $@)
	echo "Ensamblando: $< -> $@"
ifeq ($(ARCH),x86)
	$(AS) $(ASFLAGS) $< -o $@
else
	$(CC) $(CFLAGS) -c $< -o $@
endif

# ============================
# ISO (solo x86)
# ============================

os.iso: $(BUILD_DIR)/kernel.elf
ifeq ($(ARCH),x86)
	cp $(BUILD_DIR)/kernel.elf arch/x86/iso/boot/kernel.elf
	genisoimage -R \
		-b boot/grub/stage2_eltorito \
		-no-emul-boot \
		-boot-load-size 4 \
		-A os \
		-input-charset utf8 \
		-quiet \
		-boot-info-table \
		-o os.iso \
		arch/x86/iso
else
	@echo "⚠️  os.iso solo aplica para x86"
endif

# ============================
# Ejecución
# ============================
.kernel_disk/disk.txt:
	@mkdir -p .kernel_disk
	@dd if=/dev/zero of=.kernel_disk/disk.txt count=2048 bs=512

run: .kernel_disk/disk.txt all
	$(QEMU)
debug: all
	$(QEMU) -boot d -gdb tcp::26000 -S

# ============================
# Limpieza
# ============================

clean:
	rm -rf build *.iso

#debug: all
#	qemu-system-i386 -cdrom os.iso -boot d -gdb tcp::26000 -S
